# Generated by Django 4.1.3 on 2022-11-29 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lessons',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='users.lesson'),
        ),
        migrations.AlterField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='percent_salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='надбавка в процентах'),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.FloatField(blank=True, null=True, verbose_name='ставка'),
        ),
    ]
