# Generated by Django 4.1.3 on 2022-12-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0003_user_phone_alter_user_lessons_alter_user_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.AlterField(
            model_name='user',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='users', to='courses.lesson'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseType',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
