# Generated by Django 4.1.3 on 2022-12-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_lesson_course_alter_user_lessons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comment',
            field=models.TextField(blank=True, verbose_name='комментарий'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('N', 'Возможный клиент'), ('Q', 'В очереди'), ('C', 'Записан на курсы'), ('V', 'Постоянный клиент')], default='N', max_length=1, verbose_name='статус клиента'),
        ),
    ]
