# Generated by Django 4.1.3 on 2022-12-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_status_usermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='kind',
            field=models.CharField(choices=[('notify', 'notify'), ('msg', 'message')], default='msg', max_length=6),
        ),
    ]
