# Generated by Django 4.1.3 on 2022-12-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='lesson',
            name='places',
            field=models.IntegerField(default=30, verbose_name='количество мест'),
        ),
    ]
