# Generated by Django 4.1.3 on 2022-12-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_options_lesson_places'),
        ('courses', '0003_alter_coursetype_options_alter_coursetype_title'),
    ]

    operations = [
    ]
