# Generated by Django 4.1.3 on 2022-12-24 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_merge_20221210_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetype',
            options={},
        ),
    ]
